In [1]:
import matplotlib.pyplot as plt
from fastai.vision.all import *

In [2]:
time = torch.arange(0,20)
params = torch.randn(3).requires_grad_()

In [3]:
def apply_step(params,prn=True):
    
    speed = time*3 + (time-9.5)**2 + 1
    
    a,b,c = params 
    pred = a*(time**2) + b*time + c
    loss = ((pred - speed)**2).mean()
    loss.backward()
    lr = 1e-5
    params.grad
    params.data -= lr * params.grad.data
    params.grad=None
    if prn: print(loss.item())
    return pred
for i in range(10): apply_step(params)

44969.8046875
9516.1357421875
2807.175048828125
1537.5909423828125
1297.3023681640625
1251.788818359375
1243.1317138671875
1241.449462890625
1241.087646484375
1240.9747314453125


In [4]:
from fastai.vision.all import *
from torch.nn import functional
import numpy
path = untar_data(URLs.MNIST_SAMPLE)



threes = (path/'train/3').ls().sorted()
sevens = (path/'train/7').ls().sorted()
valid_3s = (path/'valid/3').ls().sorted()
valid_7s = (path/'valid/7').ls().sorted()

stacked_3s = [tensor(Image.open(o)) for o in threes]
stacked_7s = [tensor(Image.open(o)) for o in sevens]
stacked_valid3s = [tensor(Image.open(o)) for o in valid_3s]
stacked_valid7s = [tensor(Image.open(o)) for o in valid_7s]
stacked_3s = torch.stack(stacked_3s).float()/255
stacked_7s = torch.stack(stacked_7s).float()/255
stacked_valid_3s = torch.stack(stacked_valid3s).float()/255
stacked_valid_7s = torch.stack(stacked_valid7s).float()/255
average_3s = (stacked_3s).mean(0)
average_7s = (stacked_7s).mean(0)
average_valid_3s = (stacked_valid_3s).mean(0)
average_valid_7s = (stacked_valid_7s).mean(0)

def L1_loss(average,real):
    result = (average - real).abs().mean()
    return result

def mean_sq_error_loss(average,real):    
    result = ((average-real)**2).sqrt().mean()
    return result

L1_loss(average_3s,stacked_3s[0])
L1_loss(average_7s,stacked_7s[0])
L1_loss(average_valid_3s,stacked_valid_3s[0])
L1_loss(average_valid_7s,stacked_valid_7s[0])

mean_sq_error_loss(average_3s,stacked_3s[0])
mean_sq_error_loss(average_7s,stacked_7s[0])
mean_sq_error_loss(average_valid_3s,stacked_valid_3s[0])
mean_sq_error_loss(average_valid_7s,stacked_valid_7s[0])

F.l1_loss(average_3s,stacked_3s[0])
F.l1_loss(average_7s,stacked_7s[0])
F.l1_loss(average_valid_3s,stacked_valid_3s[0])
F.l1_loss(average_valid_7s,stacked_valid_7s[0])

F.mse_loss(average_3s,stacked_3s[0])
F.mse_loss(average_7s,stacked_7s[0])
F.mse_loss(average_valid_3s,stacked_valid_3s[0])
F.mse_loss(average_valid_7s,stacked_valid_7s[0])


tensor(0.0296)

In [5]:
train_x = torch.cat([stacked_3s,stacked_7s]).view(-1,28*28)
train_y = tensor([0]*len(threes) + [1]*len(sevens)).unsqueeze(1)

dset = list(zip(train_x,train_y))
x,y=dset[0]
valid_x = torch.cat([stacked_valid_3s,stacked_valid_7s]).view(-1,28*28)
valid_y = tensor([0]*len(valid_3s) + [1]*len(valid_7s)).unsqueeze(1)
valid_dset = list(zip(valid_x,valid_y))

# initialize paramters
 
def init_params(size,std=1.0): 
    return (torch.randn(size)*std).requires_grad_() 

weights = init_params(28*28,1)
bias = init_params(1)

def linear1(xb):
    return xb@weights + bias

preds = linear1(train_x)
corrects = (preds>0.0).float() == train_y
corrects.float().mean().item()
weights[0] *= 1.0001
preds = linear1(train_x)
((preds>0.0).float() == train_y.float().mean().item())

def sigmoid(x):
    return 1/(1+torch.exp(-x))

def mnist_loss(predictions,targets):
    predictions=predictions.sigmoid()
    return torch.where(targets==1,1-predictions,predictions).mean()

loss = mnist_loss(preds,train_y)


In [6]:
coll = range(15)
dl = DataLoader(coll,batch_size=5,shuffle=True)
list(dl)

ds = L(enumerate(string.ascii_lowercase))
dl = DataLoader(ds,batch_size=6,shuffle=True)
list(dl)

[(tensor([18,  8, 12, 14, 10,  0]), ('s', 'i', 'm', 'o', 'k', 'a')),
 (tensor([ 2,  3, 21, 23, 19,  6]), ('c', 'd', 'v', 'x', 't', 'g')),
 (tensor([24, 16, 15,  9,  5, 25]), ('y', 'q', 'p', 'j', 'f', 'z')),
 (tensor([20,  1, 17, 13, 11,  7]), ('u', 'b', 'r', 'n', 'l', 'h')),
 (tensor([ 4, 22]), ('e', 'w'))]

In [7]:
weights = init_params(28*28,1)
bias = init_params(1)
dl = DataLoader(dset,batch_size = 256)
xb,yb = first(dl)
valid_dl = DataLoader(valid_dset,batch_size=256)
batch = train_x[:4]
preds = linear1(batch)
loss = mnist_loss(preds,train_y[:4])
loss.backward()

In [8]:
def calc_grad(xb,yb,model):
    preds=model(xb)
    loss = mnist_loss(preds,yb)
    loss.backward()

In [9]:
weights.grad.zero_()
bias.grad.zero_()
calc_grad(batch,train_y[:4],linear1)
weights.grad.mean(),bias.grad

(tensor(7.5747e-05), tensor([0.0005]))

In [10]:
def train_epoch(model,lr,params):
    for xb,yb in dl:
        calc_grad(xb,yb,model)
        for p in params:
            p.data -= p.grad*lr
            p.grad.zero_()
            
def batch_accuracy(xb,yb):
    preds = xb.sigmoid()
    correct = (preds>.5)==yb
    return correct.float().mean()


def validate_epoch(model):
    accs = [batch_accuracy(model(xb),yb) for xb,yb in valid_dl]
    return round(torch.stack(accs).mean().item(),4)


In [11]:
batch_accuracy(linear1(batch),train_y[:4])
lr = .1
params = weights,bias
train_epoch(linear1,lr,params)
validate_epoch(linear1)

for i in range(20):
    train_epoch(linear1,lr,params)
    print(validate_epoch(linear1), end = ' ')

0.6935 0.7881 0.84 0.868 0.8831 0.8944 0.9065 0.9107 0.9159 0.9202 0.924 0.9277 0.9296 0.931 0.9334 0.9353 0.9358 0.9363 0.9372 0.9387 

In [12]:
linear_model = nn.Linear(28*28,1)
w,b = linear_model.parameters()

class BasicOptim:
    
    def __init__(self,params,lr): 
        self.params,self.lr = list(params),lr
        
    def step(self,*args,**kwargs):
        for p in self.params:
            p.data-=p.grad.data *self.lr
    
    def zero_grad(self,*args,**kwargs):
        for p in self.params:
            p.grad = None

In [13]:
lr=.1
opt = BasicOptim(linear_model.parameters(),lr)
def train_epoch(model):
    for xb,yb in dl:
        calc_grad(xb,yb,model)
        opt.step()
        opt.zero_grad()
        
validate_epoch(linear_model)

def train_model(model,epochs):
    for i in range(epochs):
        train_epoch(model)
        print(validate_epoch(model),end=' ')
        
train_model(linear_model,20)

dl = DataLoaders(dl,valid_dl)
learn = Learner(dl,nn.Linear(28*28,1),opt_func=SGD,
               loss_func=mnist_loss, metrics=batch_accuracy)

learn.fit(10,lr=lr)

def simple_net(xb):
    res = xb@w1 + b1
    res = res.max(tensor(0.0))
    res = res@w2 + b2
    return res

w1 = init_params((28*28,30))
b1 = init_params(30)
w2 = init_params((30,1))
b2 = init_params(1)

0.5464 0.8682 0.9331 0.9526 0.9619 0.9634 0.9648 0.9648 0.9663 0.9682 0.9697 0.9702 0.9721 0.9721 0.9726 0.9717 0.9717 0.9717 0.9717 0.9717 